### ISSUE TITLE
WPアーカイブテンプレの作成

### ISSUE THREAD

**Issue by 921138** [codeforoedo/website#11]
イベントやニュースの件数が5件になるまえに対応

**Comment by 921138** [comment]
参考
http://wpdocs.osdn.jp/wiki/images/wp-template-hierarchy.jpg
テーマファイルの優先順位
メモ：非推奨のはずのhome.phpがいつのまにか復活した？

**Comment by 921138** [comment]
カテゴリーで現在設定されているイベントとお知らせで一覧ページの表示内容をわけたいなどの要望はありますでしょうか？
urlは
http://codeforoedo.org/event/
や
http://codeforoedo.org/news/
となります
またカテゴリーとアーカイブ一覧（日別一覧）で表示内容を分けたいなどの要望がなければ、
archive.phpを作成します

**Comment by jumilla** [comment]
Bladeテンプレートでのテーマ書き換え作業と一緒に、私の方でやってしまいます。

**Comment by jumilla** [comment]
archive.blade.phpを作成しました。

全投稿のインデックス表示のためにhome.blade.phpを用意してありますが、中身はarchive.blade.phpを@includeしているだけです。
