### ISSUE TITLE
favicon.ico の作成

### ISSUE THREAD

**Issue by jumilla** [codeforoedo/website#14]
#3 のアウトプットを元に作成する。

**Comment by 921138** [comment]
作成してご送付します
こちら明日の午前までに準備できます

**Comment by 921138** [comment]
こちらも設定しました。HPのfaviconは調整必要そうですね。。。

**Comment by jumilla** [comment]
favicon作成ありがとうございます！

「調整必要」とありますが、後どんな作業が必要でしょうか？

**Comment by 921138** [comment]
SP用とかはよいのですが、HPの場合だと潰れてしまってるかなと。。。

**Comment by jumilla** [comment]
用語確認です。

SPはスマートフォン？
HPはホームページ？

で、「デザインの」調整が必要で、プラグインは問題なしということでしょうか？

**Comment by 921138** [comment]
はい、SPのブックマーク用はサイズ的に問題ないのですが、
パソコンのブラウザだとちょっと小さいかなぁと思いまして。
気にしなければそれまでですが
はい、今回はプラグインを使ってなので、デザインの方を調整してアップいたします

**Comment by jumilla** [comment]
はい、お願いします。
