### ISSUE TITLE
テンプレに直接書き込む内容

### ISSUE THREAD

**Issue by 921138** [codeforoedo/website#16]
header内　meta情報　title,keyword（なくてもよい）,description　後に変更
About us　文章
フッター付近　vaycancyの情報、vaycatのテキスト（現在仮）
copyright表記

**Comment by 921138** [comment]
discriptionは現在のgoole検索の仕様だとなければ、googleに任せるので、トップページ以外はなくします。
titleはwp関数で下層はいれます。
他は最低限大丈夫ですね
代わりにメンバーがまだ仮ですので、参加メンバーの入力が必要になります

**Comment by jumilla** [comment]
Webサイトに記載する参加メンバーは「運営スタッフ」にします。
β版では猫将軍だけでいいです。

**Comment by 921138** [comment]
タスクの内容は終了しているので、closedにいたします。
titleは関数で後ほど入れておきます。
