### ISSUE TITLE
トップギャラリー写真選定とCSS調整

### ISSUE THREAD

**Issue by 921138** [codeforoedo/website#19]

**Comment by jumilla** [comment]
ギャラリーの初期ロード時、2つ目以降の画像が折り返して表示されてしまっています。
認識済みでしょうか？

**Comment by 921138** [comment]
はい、スマホでも確認しました。プロパティあとで追加します。
overflow:hiddenかければ、治るかなと思います。
後ほど、修正しておきます。
このプラグイン初めてだったのですが、失敗かも。。。
