### ISSUE TITLE
GoogleMapを表示させているとスクロールできない

### ISSUE THREAD

**Issue by jumilla** [codeforoedo/website#21]
GoogleMapの上では、スクロールアクションがページのスクロールではなく地図のスクロールになってしまう。

特にiPhoneのsafariでは、最上部移動ボタンも消えてページスクロール不能となる。

地図上のスクロールを無効にし、シングルタップで別画面で地図表示という挙動にするといいと思います。

**Comment by 921138** [comment]
sp時の表示でvaycatの表示位置の修正とgoogle mapの表示域の高さ調整も一緒に行います
振る舞いに関してもお知らせ頂いた点を見ておくようにいたします

**Comment by jumilla** [comment]
vaycatボックスのY座標の位置はbottomで指定し、heightはcontentによる可変にするといいかと思いまーす！

**Comment by 921138** [comment]
地図のマウスホイール拡大縮小をfalseにしました
