### ISSUE TITLE
既定のCSSスタイルが使用できない

### ISSUE THREAD

**Issue by jumilla** [codeforoedo/website#22]
CSS宣言の冒頭で全属性をリセットされているからだと思いますが、記事中の ul>li タグなどのスタイルが反映されません。

必要な部分のみリセットするようにできませんか？

**Comment by 921138** [comment]
取り急ぎ、ul>liはスタイルシートあてました。
次回テンプレを見直す際にnormalize.cssにリセットcssを変更してもよいかもしれません

**Comment by 921138** [comment]
HPの次回リニューアル時にリセットcssを見直します

**Comment by 921138** [comment]
お返事おそくなりました。
フォントのCSSうんぬんというタスクはデフォルトのリセットcssのフォント周りのcssのことです。
ソース見なおして、必要なようであれば修正いたします
