### ISSUE TITLE
イベント告知など、記事ページでのグローバルリンクが機能しない

### ISSUE THREAD

**Issue by jumilla** [codeforoedo/website#23]
下記の記事ページ上の「About us」などのグローバルリンクが機能しません。
http://codeforoedo.org/event/shinagawa_201505_5374

ルートページからの相対リンクにする必要がある？
そもそも1ページデザインとの間でコンフリクトしている？？

解決策ありますでしょうか。

**Comment by 921138** [comment]
シングルページ用のheader-single.phpというテンプレを作成して、下層ができるまでの間は表示されないようにしましたが、後でみてみます

**Comment by 921138** [comment]
すみません、誤ってclosedにしてしまいました

**Comment by 921138** [comment]
下層コンテンツがなく、グローバルナビが存在しないため、取り急ぎ、ヘッダーはテンプレ分けます。
後ほどコンテンツ構成を考慮してテンプレも作り直しましょう
