### ISSUE TITLE
Googleウェブマスターツールへの登録

### ISSUE THREAD

**Issue by jumilla** [codeforoedo/website#24]
要Gmailアカウント。

複数人で共有したい場合、どのアカウントで登録すればよい？？

**Comment by 921138** [comment]
どなたかのGooleアカウントで登録後に設定で権限を他者のgoogleアカウントで共有できます

**Comment by 921138** [comment]
Google Analyticsの方でも同様です

**Comment by jumilla** [comment]
ウェブマスターツールに登録しました。
@921138 と @natkaori をオーナーとして追加してあります。

**Comment by 921138** [comment]
了解いたしました。後ほど確認いたします
