### ISSUE TITLE
Facebookページのいいね！した顔一覧を表示する

### ISSUE THREAD

**Issue by jumilla** [codeforoedo/website#27]
画面下部に横幅MAXで表示。

JetPackでできる？

**Comment by 921138** [comment]
JetPackで差し込みできれば、それでよいですが、socialボタンしか対応していなかった時に
https://developers.facebook.com/docs/plugins/page-plugin
新しい差し込み方です。シェアします

**Comment by natkaori** [comment]
キャッチアップできてなくてすみません―！
こちら着手しますね。
飯沢さん、シェアありがとうございます。

**Comment by natkaori** [comment]
@jumilla古川さん、@921138飯沢さん
このサイトってもうWordPress.com アカウント取得済ですか？

**Comment by natkaori** [comment]
やろうとしていることは恐らくjetpackの「いいね」機能で実装可能っぽいのですが、他のと干渉しないか／WPアカウントがあるかが現状のハードルです―。そして私がスラックを使いこなせないことも！(笑)

**Comment by jumilla** [comment]
@natkaori さん、次の事項が済んでいます。
管理画面で確認してください。
- Wordpress.comでcodeforoedoのアカウント取得
- JetPack管理画面からアカウント登録

**Comment by natkaori** [comment]
@jumilla さん、ありがとうございますー
もうちょっと触ってみますねー

**Comment by jumilla** [comment]
参考資料
http://bazubu.com/how-to-connect-wp-to-fb-23544.html

**Comment by natkaori** [comment]
差し込みはできたものの、センタリングができません(> <)
飯沢さん、CSS教えてください～！

**Comment by 921138** [comment]
イイネボタンの位置修正

**Comment by jumilla** [comment]
404ページにも表示されていますが、不要ではないでしょうか。
