### ISSUE TITLE
wordpressの拡張

### ISSUE THREAD

**Issue by 921138** [codeforoedo/website#29]

**Comment by 921138** [comment]
イベントをカテゴリにして投稿に変更

**Comment by 921138** [comment]
アーカイブファイルどうしましょう？デザイン決まったら、作成いたしますね

**Comment by jumilla** [comment]
@921138 アーカイブファイルというのは具体的に何を指していますか？
また、アーカイブファイルというもので「何の実現のために」「どう活用しようと考えて」いますか？

「デザイン決まったら」とありますが、必要なタスクならissueであげてください。

「作成する」というのも、必要であればissueであげてください。

**Comment by jumilla** [comment]
具体的なタスクに落としてください。
