### ISSUE TITLE
アイコン（正方形ロゴ）を作る

### ISSUE THREAD

**Issue by jumilla** [codeforoedo/website#3]
用途
- 公式Webサイトのfavicon
- Facebookページのアイコン
- GitHubグループのアイコン
- ...e.t.c.

※ベースとなる画像ファイルのピクセル数は、1024x1024以上で大きめに作っておいてください。

**Comment by jumilla** [comment]
飯沢さん、こちら状況はいかがですか？

**Comment by 921138** [comment]
仮アイコン作成

**Comment by 921138** [comment]
こちらも明日の午前までに再送付いたします。

**Comment by 921138** [comment]
暫定のアイコンを設定しました
