### ISSUE TITLE
記事投稿手順、ガイドラインを決める

### ISSUE THREAD

**Issue by jumilla** [codeforoedo/website#30]
当面一年間、CODE for 大江戸公式サイト運営に必要な記事投稿ができるようにします。
- 記事投稿の種類の洗い出し（イベント告知、イベント報告、ニュース等）
- WordPressでの記事投稿の表現方法決め（カテゴリを使うか、カスタム投稿タイプを使うかなど）
- WordPressでの記事本文のガイドライン決め

これは、オフラインミーティングの時にやりましょう。

**Comment by 921138** [comment]
記事投稿はカテゴリで分岐して基本は「投稿」に統一

**Comment by 921138** [comment]
記事はイベントごとに担当が投稿
