### ISSUE TITLE
facebook likeboxの位置修正

### ISSUE THREAD

**Issue by 921138** [codeforoedo/website#32]
トップページはアプリの位置へ
各ページは幅を適宜揃えて中央よせ

**Comment by 921138** [comment]
トップページは古川さんお願い致します。
下層はあとで調整しておきます

**Comment by jumilla** [comment]
Bootstrap化のときには私がやります。
この作業は2ndフェーズで。

**Comment by 921138** [comment]
likeboxちなみに現在footer.phpに夏原さんが入れてくれているようです。
プラグイン差し込みではないようです。
現在gitに上がっているfooter.phpと差分があると思いますのでお知らせします

**Comment by jumilla** [comment]
最新版はcodeforoedo.orgに上がっているものだと認識しています。
飯沢さんもgitではなくcodeforoedo.org上で作業してますよね？

**Comment by 921138** [comment]
自分が修正したファイルは一応gitにも上げて更新しました
はい最新版はcodeforoedo.orgに上がっているテーマファイルが最新ファイルで確実だと思います

**Comment by 921138** [comment]
メモ：footer.phpに404の際は表示されないように分岐を入れる

**Comment by jumilla** [comment]
それでは、これからはGit上のファイルも常に最新版を保つようにしていきましょう。

**Comment by 921138** [comment]
了解です。
