### ISSUE TITLE
すべての投稿のパーマリンクに /event/ がつく.

### ISSUE THREAD

**Issue by jumilla** [codeforoedo/website#33]
カテゴリ指定に関係なく、パーマリンクに /event/ という文字がついてしまいます。

**Comment by 921138** [comment]
カテゴリ名をチェックいれたら大丈夫だと思います。

**Comment by jumilla** [comment]
確認しましたか？

**Comment by 921138** [comment]
いましました。あとカテゴリスラッグをお知らせはinfoやtopicsなどと変更した方がよいです。
デフォルトのカテゴリがイベントだからかもしれません。

**Comment by jumilla** [comment]
確認した結果はどうでしたか？

**Comment by 921138** [comment]
大丈夫でしたよ
パーマリンクの設定が/category/postname/になっております

**Comment by jumilla** [comment]
投稿を作成すると、パーマリンクに /event/ が必ずつきます。
カテゴリを変更しても表記は変わらないようです。

**Comment by 921138** [comment]
2つにチェックをいれたから、デフォルトになったのかもです。postのurlは一つ目のカテゴリ（配列）になるはずなので

**Comment by jumilla** [comment]
カテゴリ「event」を未指定でもパーマリンクに /event/ がつきます。
デフォルト指定が意味的におかしいですね。

**Comment by jumilla** [comment]
http://liginc.co.jp/web/wp/customize/148458

このページの記事を見ると、プラグインいれずにカテゴリスラッグを使ったパーマリンク指定ができるようですよ。

**Comment by 921138** [comment]
もう既に設定ずみですよ〜　記事、カテゴリスラッグ共に日本語名から英語に変更した方がよいと思います
お知らせのスラッグ何にしますか？

**Comment by jumilla** [comment]
プラグイン「No Category Parents」はどうなりますか？

**Comment by jumilla** [comment]
カテゴリの文言・スラッグの件は、このissueの範囲外ですので別のところでお願いします。

**Comment by 921138** [comment]
プラグインはそのままでOKです。これを使って先頭につく/category/カテゴリスラッグ/記事名/
の/category/を消してます

**Comment by jumilla** [comment]
そもそも /category/ という文字列が入って来ないので不要ではないでしょうか？

**Comment by 921138** [comment]
それはこのプラグインで消しているからです、、、

**Comment by jumilla** [comment]
先ほどのLIGの記事を見ても書いてありませんし、自分でテスト用のWordPressたてて確認していますが、パーマリンクに/category/という文字列は入っていませんよ。

**Comment by jumilla** [comment]
ちなみに、LIGさんの記事は2015.02.26に書かれています。最近の情報です。

**Comment by 921138** [comment]
え〜とパーマリンクを
/%category%/%postname%/
にしているのですが、これにしないとカテゴリスラッグがでません。
んでこの設定にすると先頭に/category/
が付きます。昨日確認ずみです〜
一応ためしてみます

**Comment by 921138** [comment]
あ、プラグインなくてもいけるのかも。。。
昨日表示されたのは一体なんだったんだろ。ちょっと様子見ますね

**Comment by jumilla** [comment]
ちょっと話が通じていないですね。

プラグイン「No Category Parents」を削除しても問題なく動いています。

**Comment by 921138** [comment]
大丈夫そうですね。。すみません。私の勘違いでした。
スラッグの方は問題なさそうですか？

**Comment by jumilla** [comment]
で、本件の表題については何か対応入れましたか？そこを教えてください。

**Comment by 921138** [comment]
古川さんが投稿されたhogeの記事は/news/のスラッグになっていますが、それではダメなのですか？
何もしないで記事を書くと/event/になるということでしょうか？
普通は未投稿になるのですが、その点はわかりません

**Comment by 921138** [comment]
カテゴリにチェックをいれるとパーマリンクが先に設定されます。
あとからチェックを入れた場合は、更新しないとダメかもしれません

**Comment by jumilla** [comment]
> 以前は
> /カスタム投稿タイプ名/投稿名/
> で表示されていました。
> デフォルトだと
> /category/カテゴリー名/投稿名/
> で表示されるurlを
> /category/が取り除けるプラグインを入れています。
> エラーがでたので、一部書き換えました。深刻なエラーではありませんでした

この修正が、本件の表題の事象を引き起こしていたと思われます。

**Comment by 921138** [comment]
なるほど！確認不足でした。私がテストした環境がoedoの環境でなかったかもです。
既に過ぎたことですが、先に別環境でテストしたので、そこが古かったかもです。

**Comment by jumilla** [comment]
@921138 確認が済んだらCloseしてください。
