### ISSUE TITLE
カテゴリ名に日本語が使えない

### ISSUE THREAD

**Issue by jumilla** [codeforoedo/website#35]
カテゴリ一覧を出す場合に日本語（例えば"お知らせ"）を使いたいので、カテゴリスラッグとカテゴリ名を分けられるようにしたい。

**Comment by 921138** [comment]
分かれてますよ〜　カテゴリから編集できます。eventのカテゴリスラッグは修正しないほうがよいです

**Comment by jumilla** [comment]
> eventのカテゴリスラッグは修正しないほうがよいです

理由は？

**Comment by 921138** [comment]
カスタム投稿タイプの際に記事をeventで作成したからです
現在、5374の記事はイベント（event）にしましたので、結果的にurlはそのままです

**Comment by jumilla** [comment]
「5月時点で公開していたイベント告知のURLを変更しないため」ですね？

こちら、#33 の対応で実現できるようになったはずです。
確認お願いします。

**Comment by 921138** [comment]
はいそうです

**Comment by 921138** [comment]
closeします〜

**Comment by jumilla** [comment]
@921138 やったことの報告いれてください。

**Comment by 921138** [comment]
プラグインの削除以外はなにもしてませんよ
もともとスラッグはつかえましたし変更ないです

**Comment by jumilla** [comment]
確認したら、「確認しました」と報告いれてからCloseしてほしいんです。

**Comment by 921138** [comment]
はいそうですと確認しております。。。

**Comment by jumilla** [comment]
言葉足らずですみません。
動作確認をしてからCloseです。

「読みました」ということを知りたいのではありません。
「動作を確認しました」という報告を入れてほしいです。

**Comment by 921138** [comment]
了解です。確認ずみです
