### ISSUE TITLE
カスタム投稿タイプapp用のカスタムフィールド用意

### ISSUE THREAD

**Issue by 921138** [codeforoedo/website#36]
投稿時のカスタムフィールドの項目を指定してください
設定は自分の方で行います〜

**Comment by 921138** [comment]
因みに「アプリ」用のディレクトリ（カスタム投稿タイプ名）はappに仮に設定しましたが、他ご希望ございますか？

**Comment by jumilla** [comment]
ミーティングの時も伝えましたよー。
メモしてくださいな。
- アプリ名
- 画像
- 紹介ページのURL

でお願いします。

**Comment by 921138** [comment]
画像サイズどうしましょう？booststrapでそのまま作成されるとのことでしたが、取り急ぎフィールドだけ作成しておきますね

**Comment by jumilla** [comment]
画像サイズどうすればいいですかねー？

**Comment by 921138** [comment]
一応スマホの際にできれば高解像度に対応したいですが、画像を二枚用意してメディアクエリで切り替えは面倒なので、一枚でPC時にサイズを適宜、同比率で縮小が楽だと思います
スマホ時の表示サイズの幅、高さが実際のサイズ（ピクセル解像度）の二倍あれば綺麗です

**Comment by jumilla** [comment]
はい。それでいきましょう。
