### ISSUE TITLE
bootstrapで作成したテーマに合わせたスタイルシートの作成

### ISSUE THREAD

**Issue by 921138** [codeforoedo/website#38]
フレームワークで対応しきれない部分の対応

**Comment by jumilla** [comment]
Bootstrapを使ったテーマ作成を進めています。
HTMLの構造や、IDやクラスの指定を変更したので、これに合わせてtheme.cssを更新してください。

@921138 さん、開発中のテーマはdevelopブランチに入れてありますので、こちらから取得して作業可能です。

**Comment by jumilla** [comment]
@921138 さん、進捗の方はいかがでしょうか？
そろそろリリースしたいので、状況を教えてください。

**Comment by 921138** [comment]
ご連絡滞りすみません〜
火曜の昼辺りまでにどうにかします

**Comment by jumilla** [comment]
今のところ、どんな作業が残っているのか教えてもらえますか？

**Comment by jumilla** [comment]
@921138 さん、developブランチのソースはまだデザイン途中ですね。
一旦整理して先に進めさせていただきます。

**Comment by jumilla** [comment]
v3.0のリリース優先のため、作業引き取りました。
