### ISSUE TITLE
カスタム投稿タイプのeventをデータベース上から消す

### ISSUE THREAD

**Issue by jumilla** [codeforoedo/website#39]
@921138 

> カスタム投稿タイプのeventをデータベース上から消さないとアーカイブファイルを設定した段階でもしかしたらエラーがでるかもしれません。

**Comment by jumilla** [comment]
@921138 さん、削除するデータを特定するために、テーブル名とカラム名を教えてください。
削除するためのSQL文を提示してもいいですし、作業内容の説明があるWebページのリンクを提示するでもいいです。

**Comment by 921138** [comment]
23日（昼間）でも大丈夫でしょうか？
自分の管理しているもので一度見てみます

**Comment by jumilla** [comment]
すぐには影響ないのですよね？

アーカイブファイルを設定するのは今日・明日ではないと思います。

**Comment by 921138** [comment]
はい、すぐにはでないと思います。
でるかどうかもまだ未確認ですが、先ほどのスラッグが何もしないで表記されるということは
おかしくなる可能性があります
archive.phpがカスタム投稿タイプにも使えるからです

**Comment by jumilla** [comment]
そうですか。
このタスクは急ぎではありませんが、頭の隅に止めておいてください。

**Comment by jumilla** [comment]
アサインしておきました。
情報提示後、私をアサインしておいてください。

**Comment by 921138** [comment]
了解です〜

**Comment by 921138** [comment]
どうやらプラグインで指定して消せるのがあるみたいなので、試してみます
もし古いなどで無理な場合は再度お知らせいたします〜

**Comment by 921138** [comment]
プラグインを使用してイベントに使用したカスタムフィールド等を削除いたしました。

**Comment by jumilla** [comment]
@921138 他の人が同じ困りごとに遭遇したときのために、調べた情報の共有をお願いします。

**Comment by 921138** [comment]
カスタム投稿タイプの内容をデータベースから消すプラグイン
http://kachibito.net/wordpress/delete-custom-fields.html

**Comment by 921138** [comment]
補足
WPデータベーステーブル
http://liginc.co.jp/web/wp/other-wp/83467
不必要なデータベースの掃除がクリーンアップが出来るプラグイン
http://netaone.com/wp/wp-clean-up/
